### ISSUE TITLE
Non-consistent presence of trailing fullstops

### ISSUE THREAD

**Issue by 0x0blu** [stojanovic/huh#1]
I did not seem to find a pattern of which sentences are to be preceded by full stops.

I suggest that if it is a full sentence, we always put a full-stop at the end, or to ditch all of them altogether.

**Comment by stojanovic** [comment]
Agree. Can you send PR? :D
If not I'll try to update it as soon as I can.

**Comment by stojanovic** [comment]
Closed by #2
